# Generated by Django 4.2.7 on 2023-11-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socketapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
